packages:
  - apps/*
  - packages/*

overrides:
  js-yaml: 5.2.2
  postcss: 8.5.18
  sharp: 0.35.0

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - argon2
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

minimumReleaseAgeExclude:
  - jose@6.2.7
